# Generated by Django 4.2.7 on 2025-11-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='momo_network',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN'), ('Vodafone', 'Vodafone'), ('AT', 'AT')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='momo_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
