# Generated by Django 4.2.7 on 2025-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_cash_amount_booking_momo_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='age',
            field=models.IntegerField(blank=True, help_text='Guest age (must be 18+)', null=True),
        ),
    ]
