# Generated by Django 4.2.7 on 2025-11-07 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_roomissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_original', 'is_authorized', 'deleted_at'], name='bookings_bo_is_orig_a5d527_idx'),
        ),
    ]
