# Generated by Django 4.2.7 on 2025-11-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_add_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_original', 'status', 'deleted_at'], name='bookings_bo_is_orig_9fbcd3_idx'),
        ),
    ]
