# Generated by Django 4.2.7

from django.db import migrations, models


def migrate_room_types(apps, schema_editor):
    """Map old room_type values to new choices."""
    Room = apps.get_model('bookings', 'Room')
    mapping = {
        'standard_fan': 'standard_fan_only',
        'standard_ac': 'standard_full_night_ac',
        'twin_bed': 'short_stay_1_3_ac',
    }
    for old, new in mapping.items():
        Room.objects.filter(room_type=old).update(room_type=new)


def reverse_room_types(apps, schema_editor):
    """Reverse mapping for migration rollback."""
    Room = apps.get_model('bookings', 'Room')
    mapping = {
        'standard_fan_only': 'standard_fan',
        'standard_full_night_ac': 'standard_ac',
        'short_stay_1_3_fan': 'standard_fan',
        'short_stay_1_3_ac': 'twin_bed',
    }
    for new, old in mapping.items():
        Room.objects.filter(room_type=new).update(room_type=old)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_create_superadmins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(
                choices=[
                    ('standard_full_night_ac', 'Standard full night with A/C'),
                    ('standard_fan_only', 'Standard - Fan only'),
                    ('short_stay_1_3_fan', 'Short stay 1-3 (Fan)'),
                    ('short_stay_1_3_ac', 'Short stay 1-3 (A/C)'),
                ],
                max_length=25,
            ),
        ),
        migrations.RunPython(migrate_room_types, reverse_room_types),
    ]
