#!/bin/bash
# PostgreSQL Password Reset Script for macOS
# This script helps you reset PostgreSQL authentication

echo "=========================================="
echo "PostgreSQL Password Reset Guide"
echo "=========================================="
echo ""

# Check if pg_hba.conf has trust authentication
PG_HBA_FILE="/opt/homebrew/var/postgresql@16/pg_hba.conf"
if [ -f "$PG_HBA_FILE" ]; then
    echo "✓ Found pg_hba.conf at: $PG_HBA_FILE"
    echo ""
    echo "Current authentication settings:"
    grep -E "^local|^host" "$PG_HBA_FILE" | grep -v "^#" | head -5
    echo ""
    
    # Check if trust is already set
    if grep -q "local.*all.*all.*trust" "$PG_HBA_FILE"; then
        echo "✓ Trust authentication is already configured for local connections"
        echo ""
        echo "However, PostgreSQL may need to be RESTARTED (not just reloaded)"
        echo "for the changes to take effect."
        echo ""
    fi
else
    echo "⚠ Could not find pg_hba.conf file"
    echo "Expected location: $PG_HBA_FILE"
    echo ""
fi

echo "=========================================="
echo "STEP 1: Restart PostgreSQL"
echo "=========================================="
echo ""
echo "Option A - Using Homebrew (recommended):"
echo "  brew services stop postgresql@16"
echo "  brew services start postgresql@16"
echo ""
echo "Option B - Using pg_ctl:"
echo "  pg_ctl -D /opt/homebrew/var/postgresql@16 stop"
echo "  pg_ctl -D /opt/homebrew/var/postgresql@16 start"
echo ""
echo "Option C - Kill and restart:"
echo "  pkill -9 postgres"
echo "  brew services start postgresql@16"
echo ""
echo "=========================================="
echo "STEP 2: After restarting, test connection"
echo "=========================================="
echo ""
echo "Try connecting WITHOUT a password:"
echo "  psql -U postgres -d postgres"
echo ""
echo "If it works (no password prompt), proceed to Step 3."
echo "If it still asks for a password, the restart didn't work."
echo ""
echo "=========================================="
echo "STEP 3: Reset/Create Database User"
echo "=========================================="
echo ""
echo "Once connected (you'll see 'postgres=#'), run:"
echo ""
echo "  -- Create database if it doesn't exist"
echo "  CREATE DATABASE pama_lodge;"
echo ""
echo "  -- Drop user if exists (to start fresh)"
echo "  DROP USER IF EXISTS pama_user;"
echo ""
echo "  -- Create user with password"
echo "  CREATE USER pama_user WITH PASSWORD 'pama123';"
echo ""
echo "  -- Grant privileges"
echo "  GRANT ALL PRIVILEGES ON DATABASE pama_lodge TO pama_user;"
echo ""
echo "  -- Connect to database"
echo "  \\c pama_lodge"
echo ""
echo "  -- Grant schema privileges"
echo "  GRANT ALL ON SCHEMA public TO pama_user;"
echo ""
echo "  -- Exit"
echo "  \\q"
echo ""
echo "=========================================="
echo "STEP 4: Test Django Connection"
echo "=========================================="
echo ""
echo "After setting up the user, try:"
echo "  cd backend"
echo "  python manage.py runserver"
echo ""
echo "=========================================="

