#!/bin/bash
# PostgreSQL Setup Script for Pama Lodge
# This script helps set up the database user and database

echo "=========================================="
echo "PostgreSQL Setup for Pama Lodge"
echo "=========================================="
echo ""
echo "You'll need to enter your PostgreSQL 'postgres' user password"
echo "to run the setup commands."
echo ""
echo "Please run the following commands manually:"
echo ""
echo "1. Connect to PostgreSQL:"
echo "   psql -U postgres"
echo ""
echo "2. Once connected, run these SQL commands:"
echo ""
echo "   -- Create the database (if it doesn't exist)"
echo "   CREATE DATABASE pama_lodge;"
echo ""
echo "   -- Create or reset the user"
echo "   CREATE USER pama_user WITH PASSWORD 'pama123';"
echo "   -- OR if user exists, reset password:"
echo "   ALTER USER pama_user WITH PASSWORD 'pama123';"
echo ""
echo "   -- Grant privileges"
echo "   GRANT ALL PRIVILEGES ON DATABASE pama_lodge TO pama_user;"
echo ""
echo "   -- Connect to the database"
echo "   \\c pama_lodge"
echo ""
echo "   -- Grant schema privileges (important for PostgreSQL 15+)"
echo "   GRANT ALL ON SCHEMA public TO pama_user;"
echo ""
echo "   -- Exit"
echo "   \\q"
echo ""
echo "=========================================="
echo ""
echo "After running these commands, try starting Django again:"
echo "python manage.py runserver"
echo ""

